### ISSUE TITLE
Add ReLU layer and fully connected layer functionality

### ISSUE THREAD

**Issue by n3a9** [pytorchfi/pytorchfi#13]

**Comment by ivicii** [comment]
This would be great if this is implemented.
Hopefully, it will be fixed soon because I want to use your package because I am very intereseted in it!
Good work:)

**Comment by ma3mool** [comment]
Thank you for your feedback! We will be working on this soon, and keep you posted.

If you need a quick hack to get it working, you can modify [the lines around](https://github.com/pytorchfi/pytorchfi/blob/master/pytorchfi/core.py#L45) core.py. Hopefully we will architect a more scalable solution and push it here soon.

**Comment by n3a9** [comment]
Updated issue #44
