### ISSUE TITLE
_set_value out of bounds value

### ISSUE THREAD

**Issue by n3a9** [pytorchfi/pytorchfi#47]
In the function `_set_value` in `core.py`, the access indices are out of bounds. This may because height or width values are being used for both validations somewhere else.

```py
File "/home/pytorchfi/core.py", line 253, in _set_value output[self.CORRUPT_BATCH[i]][self.CORRUPT_C[i]][
IndexError: index 53 is out of bounds for dimension 0 with size 40
```

**Comment by ma3mool** [comment]
This was addressed with #54.
