### ISSUE TITLE
Bug : layer_types = ['all'] doesn't work well and some wishes

### ISSUE THREAD

**Issue by Force1ess** [pytorchfi/pytorchfi#65]
Hello, I have something have to tell you.
1. This repo's [GitPage](https://pytorchfi.github.io/) can't load anymore, but still showed on your repo's homepage
2. I study the usage of PytorchFI, but I find that your documentation isn't complete enough, please finish that.
3. layer_types = ['all'] doesn't work well. If you replace this parameter in your interactive demo, it will report bugs when you declare neuron fault injection.
![image](https://user-images.githubusercontent.com/72636351/134491690-6d563055-996b-45e6-87dd-e65cec2ab52b.png)

![image](https://user-images.githubusercontent.com/72636351/134491594-55e67857-590d-45b1-b5ae-27f1ec9308ff.png)
![image](https://user-images.githubusercontent.com/72636351/134491771-d7e1e30c-a7c0-48b4-8cdb-5cd53c8cb177.png)

**Comment by ma3mool** [comment]
Hi @Force1ess . 

Thanks for the feedback and issues raised. We are addressing these points and will push an update soon for both the documentation and patch for `["all"]`

**Comment by Force1ess** [comment]
Thank you for your selfless dedication to open-source world

**Comment by ma3mool** [comment]
Fixes added. We'll be pushing to pip soon, but you can get the latest code from this repo.
I'll keep working on documentation, and ping here once it's updated
